#!/usr/bin/env bash
set -euo pipefail

function timeexec
{
  /usr/bin/time -f "%U" "$@"
}

(
echo "------------"
echo "Native build"
export BIN="bin/native"
make clean
timeexec make -j`nproc`
)

(
echo "------------"
echo "RPI build"

OPT+=(-O3)
# OPT+=(-mcpu=cortex-a53)
# OPT+=(-mtune=cortex-a53)
# OPT+=(-mfloat-abi=hard)
# OPT+=(-mfpu=neon-fp-armv8)

export BIN="bin/rpi"
export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/opt/envs/rpi/lib/pkgconfig
export CXX="arm-linux-gnueabihf-g++"
export CXXFLAGS="$OPT"
export LDFLAGS=-s
make clean
timeexec make -j`nproc` $BIN/zeptosynth.exe
size=$(stat -c '%s' $BIN/zeptosynth.exe)
echo "Synth size: $size bytes"
)

