#!/usr/bin/env bash
set -euo pipefail

find src -name "*.cpp" -or -name "*.h" | xargs -L1 clang-format-11 -i

function timeexec
{
  /usr/bin/time -f "%U" "$@"
}

(
echo "------------"
echo "Native build"
export BIN="bin/native"
make clean
timeexec make -j`nproc`
)

(
echo "------------"
echo "RPI build"

OPT+=(-O3)
# OPT+=(-mcpu=cortex-a53)
# OPT+=(-mtune=cortex-a53)
# OPT+=(-mfloat-abi=hard)
# OPT+=(-mfpu=neon-fp-armv8)

export BIN="bin/rpi"
export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/opt/envs/rpi/lib/pkgconfig
export CXX="arm-linux-gnueabihf-g++"
export CXXFLAGS="$OPT"
export LDFLAGS=-s
make clean
timeexec make -j`nproc` $BIN/zeptosynth.exe $BIN/gui.exe
size=$(stat -c '%s' $BIN/zeptosynth.exe)
loc=$(find src -type f | xargs wc -l | tail -n 1)
echo "------------"
echo "Synth size: $size bytes"
echo "       Loc: $loc loc"

)

