#!/usr/bin/env bash
set -euo pipefail

PKGS=()
PKGS+=(sdl2)
PKGS+=(alsa)

SRCS=()
SRCS+=(main.cpp)
SRCS+=(synth.cpp)
SRCS+=(midi_input.cpp)
SRCS+=(audio_output_sdl.cpp)

function timeexec
{
  /usr/bin/time -f "%U" "$@"
}

(
timeexec g++ main_profile.cpp synth.cpp -o profile
)

(
echo "------------"
echo "Native build"
timeexec g++                     ${SRCS[@]} $(pkg-config ${PKGS[@]} --cflags --libs) -o zeptosynth-native
stat -c '%s' zeptosynth-native
echo ""
)

(
echo "------------"
echo "RPI build"

OPT+=(-O3)
# OPT+=(-mcpu=cortex-a53)
# OPT+=(-mtune=cortex-a53)
# OPT+=(-mfloat-abi=hard)
# OPT+=(-mfpu=neon-fp-armv8)
export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/opt/envs/rpi/lib/pkgconfig
timeexec arm-linux-gnueabihf-g++ ${OPT[@]} ${SRCS[@]} $(pkg-config ${PKGS[@]} --cflags --libs) -o zeptosynth
arm-linux-gnueabihf-strip -s zeptosynth
stat -c '%s' zeptosynth
echo ""
)

