#!/usr/bin/env bash
set -euo pipefail

readonly HOST=pi@10.1.1.5

PKGS=()
PKGS+=(sdl2)
PKGS+=(alsa)

SRCS=()
SRCS+=(main.cpp)
SRCS+=(midi_input.cpp)

echo "Native build"
(
g++ ${SRCS[@]} $(pkg-config ${PKGS[@]} --cflags --libs) -o zeptosynth-native
)

echo "RPI build"
(
export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/opt/envs/rpi/lib/pkgconfig
arm-linux-gnueabihf-g++ ${SRCS[@]} $(pkg-config ${PKGS[@]} --cflags --libs) -o zeptosynth
)

stat -c '%s' zeptosynth

scp zeptosynth $HOST:/tmp/zeptosynth
ssh $HOST /tmp/zeptosynth
