#!/usr/bin/env bash
set -euo pipefail

readonly HOST=pi@10.1.1.5

arm-linux-gnueabihf-g++ main.cpp -o zeptosynth
stat -c '%s' zeptosynth

scp zeptosynth $HOST:/tmp/zeptosynth
ssh $HOST /tmp/zeptosynth
